### ISSUE TITLE
Stuck at challenge: Unique Email Addresses

### ISSUE THREAD

**Issue by Ravineesh** [neo4j-graphacademy/app-python#4]
I've been trying to pass the test case for Challenge: Unique email addresses, but the test case is failing:

![image](https://user-images.githubusercontent.com/6857904/162719883-c797b3de-56e1-47e2-9d8a-fcbc8f1d0fef.png)

To complete the task, one should insert the constraints in the Neo4j sandbox but running the constraint in the sandbox is giving me the below error. Before applying this constraint there are a few nodes, which already share the same email address, as result the constraint is failing. 

![image](https://user-images.githubusercontent.com/6857904/162719828-2c74ae43-bcb1-4fef-9434-a25a15ed6548.png)

**Comment by Ravineesh** [comment]
This issue is resolved now.!

**Comment by shashank1623** [comment]
how you solve this error
can you help me plss!

**Comment by adam-cowley** [comment]
This error occurs when two nodes already exist with the same property, meaning the constraint is already violated and can't be created.

If you delete one of the users with that email address, you should be able to create the constraint.


```
MATCH (u:User)
WITH u.email AS email, collect(u) AS users
WHERE size(users) > 1
FOREACH (u IN users | DETACH DELETE u)
```

**Comment by shashank1623** [comment]
> This error occurs when two nodes already exist with the same property, meaning the constraint is already violated and can't be created.
> 
> If you delete one of the users with that email address, you should be able to create the constraint.
> 
> ```
> MATCH (u:User)
> WITH u.email AS email, collect(u) AS users
> WHERE size(users) > 1
> FOREACH (u IN tail(users) | DETACH DELETE u)
> ```

thanks a  lot but still this application has lot of error after completing all the challenges.

**Comment by adam-cowley** [comment]
Did this query solve this issue for you?  Can you please open a new issue with the details of the other errors?

**Comment by hlin863** [comment]
Where did you run the code for running in the sandbox?
